{
 "title": "Router",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "port_mem_used_kb", "legendFormat": "Used" },
    { "expr": "port_mem_free_kb", "legendFormat": "Free" },
    { "expr": "port_mem_buff_kb", "legendFormat": "Buffers" },
    { "expr": "port_mem_shrd_kb", "legendFormat": "Shared" },
    { "expr": "port_mem_cached_kb", "legendFormat": "Cached" }
   ]
  },
  {
   "title": "Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(port_rx{command=\"display_portstatistics_portnum_1\"}[5m])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(port_rx_uc{command=\"display_portstatistics_portnum_1\"}[5m])",
     "legendFormat": "Unicast"
    },
    { "expr": "rate(port_rx_mc[5m])", "legendFormat": "Multicast" },
    { "expr": "rate(port_rx_bc[5m])", "legendFormat": "Broadcast" }
   ]
  },
  {
   "title": "Transmited Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    { "expr": "rate(port_tx[5m])", "legendFormat": "Total" },
    { "expr": "rate(port_tx_bc[5m])", "legendFormat": "Broadcast" },
    { "expr": "rate(port_tx_uc[5m])", "legendFormat": "Unicast" },
    { "expr": "rate(port_rx_mc[5m])", "legendFormat": "Multicast" }
   ]
  },
  {
   "title": "LAN Interface Speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "rate(port_rx_byte_ok[5m])", "legendFormat": "Inbound" },
    { "expr": "rate(port_tx_byte_ok[5m])", "legendFormat": "Outbound" }
   ]
  }
 ]
}